---
# tasks file for lighthouse-role
- name: Install component for NGINX
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Generate NGINX config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: "nginx"
    group: "nginx"
- name: Owner and group for default.conf
  become: true
  ansible.builtin.file:
    path: "/etc/nginx/conf.d/"
    state: directory
    recurse: true
    owner: "nginx"
    group: "nginx"
- name: Create Lighthouse directory
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
    recurse: true
    mode: '0755'
    owner: nginx
    group: nginx
- name: Clone from Git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
- name: Owner and group for /var/www/lighthouse
  become: true
  ansible.builtin.file:
    path: "/var/www/lighthouse"
    state: directory
    recurse: true
    owner: "nginx"
    group: "nginx"
# САМЫЙ ВАЖНЫЙ ПАРАМЕТР БЕЗ КОТОРОГО ВСЕ СТРАНИЦЫ НЕДОСТУПНЫ!!!
- name: Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled
- name: Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
    owner: "nginx"
    group: "nginx"
  notify: Start nginx